### ISSUE TITLE
crud_service工具问题

### ISSUE THREAD

**Issue by ytl142857** [FISCO-BCOS/python-sdk#150]
使用`crud_service`创建`table`需要设置`key`，但是
1. 插入`entry`时并不检查key是否重复
2. 使用`CRUDService.select()`方法时，`condition`内必须含有对`key`的限制
3. 基于(2)，调用`CRUDService.desc()`方法时，会报错
`Must set condition for the primary key`

**Comment by cyjseagull** [comment]
> 3\. 基于(2)，调用`CRUDService.desc()`方法时，会报错
>     `Must set condition for the primary key`

第3个问题已经修复，可以拉取最新代码
