### ISSUE TITLE
[Critical] 当前版本的Python-sdk 在合约调用的参数解析，以及对节点返回结果的解析都存在问题。

### ISSUE THREAD

**Issue by zjianwu** [FISCO-BCOS/python-sdk#169]
下载安装当前版本的Python SDK，用python sdk自带控制台操作，
1. 部署 HelloWorld 合约，正常。
2. ./console.py call HelloWorld address get
    Fisco 节点能正常返回结果，但是Client端无法正确解析，结果如下。
--------------------------------------------------------
$ python3 ./console.py call HelloWorld 0x83592a3cf1af302612756b8687c8dc7935c0ad1d get

INFO >> user input : ['call', 'HelloWorld', '0x83592a3cf1af302612756b8687c8dc7935c0ad1d', 'get']

contract_abi_path contracts/HelloWorld.abi, contract_bin_path contracts/HelloWorld.bin
INFO>> client info: channel 127.0.0.1:20202,groupid :1,crypto type:ECDSA,ssl type:ECDSA
INFO >> call HelloWorld , address: 0x83592a3cf1af302612756b8687c8dc7935c0ad1d, func: get, args:[]
0x0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000d48656c6c6f2c20576f726c642100000000000000000000000000000000000000
[Exception] (when decoding the output in response):
 TypeError: isinstance() arg 2 must be a type or tuple of types

Parse tree:
<Node matching "">  <-- *** We were here. ***
reuslt: currentBlockNumber, 
reuslt: output, 
reuslt: status, 
--------------------------------------
以上例外输出本人新增于 bcosclient.py 中BcosClient类的方法 call(...)中
错误发生于下面语句：
decoderesult = decode_abi(fn_output_types,decode_hex(outputdata))
即 decode_abi() 调用出错，没能正常解析出返回的结果，只是解析出了返回结果的几个 keys，而没有正确解析出 Values。

3. ./console.py sendtx HelloWorld address set "some string."
    Client 就不能正确编码输入的参数以提交给Fisco 节点，以上操作无法调用合约中的set(...)函数以更新字符串。
命令执行的终端输出如下：
$ python3 ./console.py sendtx HelloWorld last set "some string."

INFO >> user input : ['sendtx', 'HelloWorld', 'last', 'set', 'some string.']

contract_abi_path contracts/HelloWorld.abi, contract_bin_path contracts/HelloWorld.bin
INFO>> client info: channel 127.0.0.1:20202,groupid :1,crypto type:ECDSA,ssl type:ECDSA
INFO >> sendtx HelloWorld , address: 0x83592a3cf1af302612756b8687c8dc7935c0ad1d, func: set, args:['some string.']
ERROR >> execute sendtx failed
ERROR >> error information: TypeError: isinstance() arg 2 must be a type or tuple of types

Parse tree:
<Node matching "">  <-- *** We were here. ***

**Comment by coderkentzhang** [comment]
cause: eth-abi 3.0.1 has requirement parsimonious<0.9.0,>=0.8.0, but you'll have parsimonious 0.10.0 which is incompatible.
install parsimonious  0.8 instead 
or uses branch "dev202209"

**Comment by zjianwu** [comment]
Thanks for the hint.
