### ISSUE TITLE
【新版合约部署问题】合约部署报错信息有未安装的环境

### ISSUE THREAD

**Issue by lgmmomo** [FISCO-BCOS/python-sdk#174]
<img width="1261" alt="image" src="https://user-images.githubusercontent.com/49273693/191408166-81ec0b2d-c53f-4462-9c3a-ef4a637ee630.png">
请问现在是改用nodejs吗？之前环境没有安装似乎。

**Comment by coderkentzhang** [comment]
应该是没有找到solc，所以会去找nodejs，按路径确认一下是否能找到solc执行文件

**Comment by lgmmomo** [comment]
额，主要是之前我没改配置，和之前bcos官网一键搭链的账户配置不同导致没有找solc，更改client_config.py中账户名solc路径配置后可以了。
