### ISSUE TITLE
也请更新（升级）Python_SDK 所依赖 solc (Solidity 编译器)

### ISSUE THREAD

**Issue by zjianwu** [FISCO-BCOS/python-sdk#183]
到现在新推出的 python sdk （2022年9月），还只是支持 solc-0.4.25 (当然我不清楚这个版本是如何对应的)，下面一些常用的函数或表达式都不能支持。
string.concat(...)
type(uint).min, type(uint).max

**Comment by coderkentzhang** [comment]
可以参见说明文档自行下载不同版本的编译器
