### ISSUE TITLE
执行pip install -r requirements.txt 命令报错

### ISSUE THREAD

**Issue by freezehe** [FISCO-BCOS/python-sdk#186]
问题描述：阿里云服务器：版本CentOS Linux release 8.5.2111
python版本 3.6.8
![image](https://user-images.githubusercontent.com/11324122/222635494-b6b9795f-1f9b-4bbc-91c6-3bd0b9de8031.png)

执行下载依赖命令报错
ERROR: Could not find a version that satisfies the requirement exceptiongroup==1.1.0 (from versions: 0.0.0a0)
ERROR: No matching distribution found for exceptiongroup==1.1.0
![image](https://user-images.githubusercontent.com/11324122/222635551-ab6ec97b-1cc4-4d0a-bb60-9910657c8932.png)

**Comment by coderkentzhang** [comment]
可以打开requirements.txt 把exceptiongroup==1.1.0 的版本号约束去掉试试。如有其他库依赖缺失，也可以依法尝试。
另外，建议加其他源，如清华的。也有可能你用的这个镜像版本不全。

**Comment by tenthousands** [comment]
这是由于阿里云的源在仓库中没有找到exceptiongroup==1.1.0版本所导致的
