### ISSUE TITLE
win10 安装python-sdk报错

### ISSUE THREAD

**Issue by freezehe** [FISCO-BCOS/python-sdk#187]
问题描述：**win10系统**，参考文档进行安装，**python版本3.10.5**，**fisco版本2.9.2**

![image](https://user-images.githubusercontent.com/11324122/222684024-5ffd2422-d576-4955-82a0-90046c4a46dd.png)
![image](https://user-images.githubusercontent.com/11324122/222684441-7091b399-8228-4b6f-90eb-f78d9763d7ff.png)

问题1：python-sdk没有console.py文件，我理解是console2.py对应的fisco 2版本，相应的配置我都配置了，包括solc，sdk证书

![image](https://user-images.githubusercontent.com/11324122/222684889-255a059b-4cc9-4e8b-888e-0bd69f3d1917.png)
![image](https://user-images.githubusercontent.com/11324122/222685051-692c9a99-6229-4968-b279-1db2abcb093b.png)
![image](https://user-images.githubusercontent.com/11324122/222685336-d9b7bc3c-42c6-4787-bf1b-8ab19a51083a.png)

问题2：执行.console2.py getNodeVersion 报错
![image](https://user-images.githubusercontent.com/11324122/222685424-388a711a-3fa3-4edd-b40d-f0176e359b47.png)

**Comment by coderkentzhang** [comment]
建议你参照
https://blog.csdn.net/m0_60649037/article/details/123093475

这里自行修改一下。或者使用3.10以下的版本如3.9.5

**Comment by coderkentzhang** [comment]
已经更新版本说明：
Python环境：python 3.6.3, 3.7.x ,3.8.x ,3.9.x (python 3.10+的语法对依赖库的要求有较大差异，尚未适配)
console使用说明：
如要使用2.x的控制台，把console.py换成console2.py。
如要使用3.x的控制台，把console.py换成console3.py。

如按默认示例运行到console.py ,会有屏幕提示
