### ISSUE TITLE
console3.py CONSENSUS cmd error

### ISSUE THREAD

**Issue by xp007123** [FISCO-BCOS/python-sdk#192]
执行RPC Query Cmds相关命令正常，但执行CONSENSUS cmd就会报错，示例命令: python3 console3.py addSealer 27582c8*** ,报错文件如下：
[cpp_sdk_log_2023031416.09.log](https://github.com/FISCO-BCOS/python-sdk/files/10966091/cpp_sdk_log_2023031416.09.log)

**Comment by coderkentzhang** [comment]
目前console3.py未完整实现addSealer命令。对网络的维护建议通过控制台或webase进行。sdk主要用于合约开发和调用。
如有在pythonsdk端完整管理链的需求，建议
1： 参照控制台的实现和底层链文档扩展指令，不会很难，主要是调用系统合约。
2： 提交需求，官方项目后续排期实现。

**Comment by xp007123** [comment]
OK，我改改Java控制台用吧，主要是python可以在终端输入命令获得执行结果，JavaConsole非要开个窗口流。
