### ISSUE TITLE
运行demo代码时出现问题

### ISSUE THREAD

**Issue by Lorenz5622** [FISCO-BCOS/python-sdk#194]
在运行demo 中的demo_transaction2.py文件时出现了以下错误：
<img width="504" alt="image" src="https://github.com/FISCO-BCOS/python-sdk/assets/91588395/bccba4cd-d4f3-48b8-84e4-eb4f0ab6c2d9">
请问该如何解决？
在contracts中能够看到helloworld6.sol被编译完成，已有helloworld6.bin和helloworld6.abi文件

**Comment by coderkentzhang** [comment]
检查client_config.py 里的编译器路径配置。这个demo会用配置的编译器去编译一次，如果找不到编译器路径，就会默认去用solcjs编译，而你的环境又没有安装nodejs，所以就异常了
