### ISSUE TITLE
运行testclient.py报错

### ISSUE THREAD

**Issue by hitmgr** [FISCO-BCOS/python-sdk#197]
运行时报错需要bin/accounts/pemtest.pem 
<img width="1118" alt="image" src="https://github.com/FISCO-BCOS/python-sdk/assets/45727640/c90796d8-3723-4116-9c72-ed38b860fe4d">
但实际上目录只存在文件.keystore，不存在.pem
<img width="353" alt="image" src="https://github.com/FISCO-BCOS/python-sdk/assets/45727640/ef84ff1a-97c9-4364-9315-dccafba19b3c">

**Comment by coderkentzhang** [comment]
测试代码，建议自行生成pem文件
