### ISSUE TITLE
console2.py execute rpc command error

### ISSUE THREAD

**Issue by jmzhuzhonghua** [FISCO-BCOS/python-sdk#200]
Environment:
      OS: Ubuntu 20.04
      Python: 3.8.10
      Node : 2.9 GM version

(venv3) root@SD-20210414ZMQA:~/bcos/python-sdk# python console2.py getBlockNumber

INFO >> user input : ['getBlockNumber']

INFO >> BcosClient:  rpc:RPC connection http://118.195.226.179:8545
,groupid :1,crypto type:GM,ssl type:GM
1
ERROR >> execute getBlockNumber failed
ERROR >> error information: (-1, None, "getBlockNumber failed, params: [1], response: null, error information: 'Response' object has no attribute 'cb_context'")

(venv3) root@SD-20210414ZMQA:~/bcos/python-sdk#

**Comment by coderkentzhang** [comment]
issue fixed. in utils/request.py
