### ISSUE TITLE
Smart contract error not returned

### ISSUE THREAD

**Issue by ezhkovskii** [FISCO-BCOS/python-sdk#203]
The smart contract has a function
function _checkOwner() internal view virtual {
         require(owner() == _msgSender(), "Ownable: caller is not the owner");
     }

I expect the SDK to return an error "caller is not the owner" if user != owner, but If there was an error in the smart contract, it is not returned.
abi_parser.parse_output(fn_name, output)  function returns empty result.
status in transaction = 16 - RevertInstruction.

How can I read an error from a smart contract?

**Comment by coderkentzhang** [comment]
cause error only string message return ,use sample code: 
if str(status) is not '0':
        outputbody = output[10:] #去掉0x[func_sig]共10个字符
        errmsg = decode_single("(string)", decode_hex(outputbody))

**Comment by ezhkovskii** [comment]
> cause when error only string message return ,use sample code: if str(status) is not '0': outputbody = output[10:] #去掉0x[func_sig]共10个字符 errmsg = decode_single("(string)", decode_hex(outputbody))

спасибо!
