### ISSUE TITLE
智能合约抛出的事件如何监听

### ISSUE THREAD

**Issue by TXZdream** [FISCO-BCOS/python-sdk#85]
智能合约里面有一个emit方法，作用是抛出一个事件，但是在文档和demo中，我都只看到可以从调用合约的返回值里获取log从而看到事件，找不到如何监听这个event的方法。所以这个有没有提供监听的途径呢？或者说我有没有办法通过一个for循环来轮询获得这个log呢？

**Comment by cyjseagull** [comment]
Python SDK暂时没有提供事件监听功能，Java SDK是支持的。
后续版本，我们会支持事件监听。

**Comment by TXZdream** [comment]
好的谢谢~我是用python的，不过我是直接轮询交易获得log信息来使用的
