### ISSUE TITLE
请问python-sdk支持调用以struct作为入参的智能合约吗.

### ISSUE THREAD

**Issue by liuxin949490** [FISCO-BCOS/python-sdk#98]
如题.
谢谢.
还想请问. 
python sdk之后会继续开发吗, 我们在做技术选型. 希望能找一个稳定的框架. 
谢谢~

**Comment by coderkentzhang** [comment]
python-sdk会继续开发。目前已经基本稳定。如fisco-bcos有新特性会增量跟进。
是否支持struct取决于abi和编译器版本。目前版本没有特意测试。
